using System.Text.Json;
using FluentAssertions;
using Sleeper.RosterReport.Recap;

namespace Sleeper.RosterReport.Tests;

/// <summary>
/// The data layer decides franchise-vs-owner continuity once, and every page on the site reads
/// that decision. Getting it wrong produces wrong all-time records everywhere at once, so the
/// generated file is asserted directly rather than trusted.
/// </summary>
public class LeagueDataTests
{
    private static readonly string DataPath =
        Path.Combine(RecapPaths.WorkspaceRoot, "site", "src", "data", "league.json");

    private static JsonElement Load()
    {
        File.Exists(DataPath).Should().BeTrue(
            $"site/src/data/league.json should be generated by `site-data` before the site is built (looked in {DataPath})");

        return JsonDocument.Parse(File.ReadAllText(DataPath)).RootElement.Clone();
    }

    [Fact]
    public void HeadToHeadIsSymmetric()
    {
        var root = Load();
        var pairs = root.GetProperty("records").GetProperty("head_to_head").EnumerateArray().ToList();
        pairs.Should().NotBeEmpty();

        foreach (var pair in pairs)
        {
            var owner = pair.GetProperty("owner_name").GetString();
            var opponent = pair.GetProperty("opponent_name").GetString();

            owner.Should().NotBe(opponent, "an owner cannot play himself");

            var mirror = pairs.SingleOrDefault(p =>
                p.GetProperty("owner_name").GetString() == opponent &&
                p.GetProperty("opponent_name").GetString() == owner);

            mirror.ValueKind.Should().NotBe(JsonValueKind.Undefined,
                $"every pairing needs both directions ({owner} vs {opponent})");

            mirror.GetProperty("wins").GetInt32().Should().Be(pair.GetProperty("losses").GetInt32());
            mirror.GetProperty("losses").GetInt32().Should().Be(pair.GetProperty("wins").GetInt32());
        }
    }

    [Fact]
    public void OwnerCareerTotalsMatchTheirSeasons()
    {
        var root = Load();

        foreach (var owner in root.GetProperty("owners").EnumerateArray())
        {
            var seasons = owner.GetProperty("seasons").EnumerateArray().ToList();
            var career = owner.GetProperty("career");

            career.GetProperty("seasons_played").GetInt32().Should().Be(seasons.Count);
            career.GetProperty("wins").GetInt32().Should()
                .Be(seasons.Sum(s => s.GetProperty("wins").GetInt32()));
            career.GetProperty("losses").GetInt32().Should()
                .Be(seasons.Sum(s => s.GetProperty("losses").GetInt32()));
        }
    }

    /// <summary>
    /// A franchise that changes hands must not hand its record to the incoming owner, and the
    /// departing owner must not still read as active just because he played the last completed
    /// season. This is the specific failure the continuity model exists to prevent.
    /// </summary>
    [Fact]
    public void FranchiseHandoffDoesNotTransferRecordOrActiveStatus()
    {
        var root = Load();
        var franchises = root.GetProperty("franchises").EnumerateArray().ToList();
        var owners = root.GetProperty("owners").EnumerateArray().ToList();

        var handedOff = franchises
            .Where(f => f.TryGetProperty("current_owner_name", out var current)
                && f.GetProperty("timeline").EnumerateArray().Any()
                && f.GetProperty("timeline").EnumerateArray().Last()
                    .GetProperty("owner_name").GetString() != current.GetString())
            .ToList();

        handedOff.Should().NotBeEmpty("the 2026 season includes an ownership change");

        foreach (var franchise in handedOff)
        {
            var incoming = franchise.GetProperty("current_owner_name").GetString();
            var departing = franchise.GetProperty("timeline").EnumerateArray().Last()
                .GetProperty("owner_name").GetString();

            var incomingOwner = owners.Single(o => o.GetProperty("name").GetString() == incoming);
            var departingOwner = owners.Single(o => o.GetProperty("name").GetString() == departing);

            incomingOwner.GetProperty("active").GetBoolean().Should().BeTrue();
            incomingOwner.GetProperty("career").GetProperty("seasons_played").GetInt32().Should().Be(0,
                "an incoming owner inherits the roster, not the results");

            departingOwner.GetProperty("active").GetBoolean().Should().BeFalse(
                "a departed owner is not active even though he played the most recent completed season");
            departingOwner.GetProperty("career").GetProperty("seasons_played").GetInt32().Should()
                .BeGreaterThan(0, "a departed owner keeps the record he earned");

            franchise.GetProperty("owner_history").EnumerateArray()
                .Select(o => o.GetString())
                .Should().ContainInOrder(departing, incoming);
        }
    }

    [Fact]
    public void EverySeasonStandingsRowHasAFranchiseAndOwner()
    {
        var root = Load();
        var seasons = root.GetProperty("seasons").EnumerateArray().ToList();
        seasons.Should().NotBeEmpty();

        foreach (var season in seasons)
        {
            var standings = season.GetProperty("standings").EnumerateArray().ToList();
            standings.Should().NotBeEmpty();

            foreach (var row in standings)
            {
                row.GetProperty("franchise_id").GetInt32().Should().BeGreaterThan(0);
                row.GetProperty("owner_name").GetString().Should().NotBeNullOrWhiteSpace();
                row.GetProperty("owner_name").GetString().Should().NotStartWith("Roster ",
                    "an unresolved owner means the lore join key is broken");
            }
        }
    }
}
